import type { BuilderId } from './schemas'
import { isValidUuidV4, mintUuidV4 } from './auth/uuidV4'

/**
 * Anonymous owner identity for VibeCity (REQ-009).
 *
 * Ported from VibeRacer's `src/lib/racerId.ts`. Differences from VibeRacer:
 *   - Cookie name is `vibecity.builderId` (separate namespace from VibeRacer
 *     so a player visiting both projects gets a distinct id per project).
 *   - Type alias is `BuilderId` (see `BuilderIdSchema` in `./schemas`).
 *
 * Lifecycle:
 *   - First visit: caller issues `newBuilderId()` and sets the cookie.
 *   - Subsequent visits: server components read via `cookies()` directly.
 *   - Cookie is long-lived (1 year) so a builder keeps ownership of cities
 *     they create across visits without sign-up.
 *
 * The id has no PII. It is a v4 UUID generated by `crypto.randomUUID()`.
 */
export const BUILDER_ID_COOKIE = 'vibecity.builderId'
export const BUILDER_ID_COOKIE_MAX_AGE_SEC = 60 * 60 * 24 * 365

/**
 * UUID v4 shape check for a builder id. Delegates to the generic
 * `isValidUuidV4` so VibeCity and VibeRacer accept the same id format.
 */
export function isValidBuilderId(value: string): boolean {
  return isValidUuidV4(value)
}

/**
 * Mints a fresh builder id. Call from the route handler that issues
 * the cookie on first visit. Delegates to `mintUuidV4`.
 */
export function newBuilderId(): BuilderId {
  return mintUuidV4()
}
